from __future__ import annotations

import importlib.util
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INSTALL = ROOT / "scripts" / "install.sh"
WRAPPER = ROOT / "scripts" / "codex-wrapper.bash"
ENV_MODULE = ROOT / "codexchange_proxy" / "env_file.py"
COX_CONFIG = ROOT / "scripts" / "cox-config"


def _load_env_module():
    spec = importlib.util.spec_from_file_location("p88_env_file", ENV_MODULE)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _function_body(text: str, name: str, next_name: str) -> str:
    start = text.index(f"{name}() {{")
    end = text.index(f"{next_name}() {{", start)
    return text[start:end]


def _run_bash(script: str, *, env: dict[str, str], timeout: int = 20) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", "--noprofile", "--norc", "-c", script],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env,
        check=False,
        timeout=timeout,
    )


def test_p88_static_contract_never_sources_runtime_env_files() -> None:
    install_text = INSTALL.read_text(encoding="utf-8")
    cox_wrapper = _function_body(install_text, "write_cox_wrapper", "write_codex_wrapper")
    canonical = WRAPPER.read_text(encoding="utf-8")
    standard = (ROOT / "scripts" / "cox-start").read_text(encoding="utf-8")
    reasoning = (ROOT / "scripts" / "cox-start-reasoning").read_text(encoding="utf-8")
    config = COX_CONFIG.read_text(encoding="utf-8")

    assert 'source "\\$ENV_FILE"' not in cox_wrapper
    assert '. "\\$ENV_FILE"' not in cox_wrapper
    assert 'exec "$INSTALL_DIR/.venv/bin/cox" "\\$@"' in cox_wrapper
    assert "__codexchange_source_env_file" not in canonical
    assert '. "$env_file"' not in canonical
    assert "__codexchange_load_env_file_data" in canonical
    assert '"$install_dir/codexchange_proxy/env_file.py" "$env_file"' in canonical
    for text in (standard, reasoning):
        assert 'source "$ENV_FILE"' not in text
        assert '. "$ENV_FILE"' not in text
        assert 'codexchange_proxy/env_file.py" emit-runtime-nul' in text
    assert 'set-export "$ENV_FILE" "$key" "$value"' in config
    assert "eval " not in canonical


def test_p88_data_parser_ignores_commands_and_filters_dangerous_names(tmp_path: Path) -> None:
    module = _load_env_module()
    marker = tmp_path / "executed.txt"
    env_file = tmp_path / "env"
    env_file.write_text(
        "# inert configuration\n"
        f"printf executed > {marker}\n"
        "export COX_MODEL='literal $(printf not-executed)'\n"
        "export COX_MODEL_API_KEY='dummy-secret'\n"
        f"export BASH_ENV={tmp_path / 'dangerous.sh'}\n",
        encoding="utf-8",
    )

    values = module.read_env_exports(env_file)
    runtime = module.runtime_env_exports(env_file)

    assert not marker.exists()
    assert values["COX_MODEL"] == "literal $(printf not-executed)"
    assert values["BASH_ENV"].endswith("dangerous.sh")
    assert runtime["COX_MODEL_API_KEY"] == "dummy-secret"
    assert "BASH_ENV" not in runtime


def test_p88_writer_round_trips_special_values_as_single_line_inert_data(tmp_path: Path) -> None:
    module = _load_env_module()
    marker = tmp_path / "writer-executed.txt"
    env_file = tmp_path / "env"
    values = {
        "COX_MODEL": f"model'; printf executed > {marker}; #\nsecond-line",
        "COX_MODEL_API_KEY": "key with spaces = $() ' quotes \\ slash",
        "COX_REASONING_EFFORT": "high",
    }

    module.write_env_exports(
        env_file,
        values,
        header=("# codexchange local environment", "# Generated by p88 test"),
    )

    assert module.read_env_exports(env_file) == values
    assert not marker.exists()
    assert len(env_file.read_text(encoding="utf-8").splitlines()) == 5
    sourced = _run_bash(
        'set -euo pipefail; source "$ENV_FILE"; printf "%s" "$COX_MODEL"',
        env={**os.environ, "ENV_FILE": str(env_file)},
    )
    assert sourced.returncode == 0, sourced.stderr
    assert sourced.stdout == values["COX_MODEL"]
    assert not marker.exists()


def test_p88_canonical_loader_exports_only_allowed_inert_values(tmp_path: Path) -> None:
    marker = tmp_path / "loader-executed.txt"
    env_file = tmp_path / "env"
    env_file.write_text(
        f"printf executed > {marker}\n"
        "export COX_MODEL='safe-model $(printf inert)'\n"
        "export COX_PORT=18888\n"
        f"export BASH_ENV={tmp_path / 'dangerous.sh'}\n",
        encoding="utf-8",
    )
    script = r'''
set -euo pipefail
source "$WRAPPER"
unset COX_MODEL COX_PORT BASH_ENV
COX_ENV_FILE="$ENV_FILE"
export COX_ENV_FILE
__codexchange_load_env_file_data "$PYTHON" "$ROOT"
printf 'model=%s\nport=%s\nbash_env=%s\n' "$COX_MODEL" "$COX_PORT" "${BASH_ENV-unset}"
'''
    completed = _run_bash(
        script,
        env={
            **os.environ,
            "WRAPPER": str(WRAPPER),
            "ENV_FILE": str(env_file),
            "PYTHON": sys.executable,
            "ROOT": str(ROOT),
            "PYTHONPATH": str(ROOT),
        },
    )

    assert completed.returncode == 0, completed.stderr
    assert "model=safe-model $(printf inert)" in completed.stdout
    assert "port=18888" in completed.stdout
    assert "bash_env=unset" in completed.stdout
    assert not marker.exists()


def test_p88_canonical_loader_fails_closed_on_malformed_export(tmp_path: Path) -> None:
    env_file = tmp_path / "env"
    env_file.write_text("export COX_MODEL='unterminated\n", encoding="utf-8")
    script = r'''
source "$WRAPPER"
COX_ENV_FILE="$ENV_FILE"
export COX_ENV_FILE
__codexchange_load_env_file_data "$PYTHON" "$ROOT"
'''
    completed = _run_bash(
        script,
        env={
            **os.environ,
            "WRAPPER": str(WRAPPER),
            "ENV_FILE": str(env_file),
            "PYTHON": sys.executable,
            "ROOT": str(ROOT),
            "PYTHONPATH": str(ROOT),
        },
    )

    assert completed.returncode == 70
    assert "invalid env data at line 1" in completed.stderr
    assert "unterminated" not in completed.stderr


def test_p88_legacy_cox_config_writes_special_model_as_inert_data(tmp_path: Path) -> None:
    module = _load_env_module()
    marker = tmp_path / "config-executed.txt"
    env_file = tmp_path / "env"
    model = f'p88-model"; printf executed > {marker}; #'
    completed = subprocess.run(
        ["bash", str(COX_CONFIG), "set-model", model],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env={
            **os.environ,
            "COX_PROJECT": str(ROOT),
            "COX_PYTHON": sys.executable,
            "COX_ENV_FILE": str(env_file),
            "CODEX_CONFIG_FILE": str(tmp_path / "codex" / "config.toml"),
            "COX_CONFIG_RESTART_THINKING": "0",
            "PYTHONPATH": str(ROOT),
        },
        check=False,
        timeout=20,
    )

    assert completed.returncode == 0, completed.stderr
    assert module.read_env_exports(env_file)["COX_MODEL"] == model
    assert not marker.exists()
    sourced = _run_bash(
        'set -euo pipefail; source "$ENV_FILE"; printf "%s" "$COX_MODEL"',
        env={**os.environ, "ENV_FILE": str(env_file)},
    )
    assert sourced.returncode == 0, sourced.stderr
    assert sourced.stdout == model
    assert not marker.exists()
