#!/usr/bin/env bash
set -euo pipefail

INSTALL_DIR="${DEEPSEEK_PROXY_INSTALL_DIR:-$HOME/.local/share/deepseek-responses-proxy}"
REPO_URL="${DEEPSEEK_PROXY_REPO_URL:-https://github.com/Awenforever/CoDeepSeedeX.git}"
BIN_DIR="${DEEPSEEK_PROXY_BIN_DIR:-$HOME/.local/bin}"
CONFIG_DIR="${DEEPSEEK_PROXY_CONFIG_DIR:-$HOME/.config/deepseek-responses-proxy}"
ENV_FILE="${DEEPSEEK_PROXY_ENV_FILE:-$CONFIG_DIR/env}"
DRY_RUN=0
INSTALL_CODEX_PROFILE=1
NON_INTERACTIVE=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --non-interactive) NON_INTERACTIVE=1 ;;
    --install-dir) INSTALL_DIR="$2"; shift ;;
    --repo-url) REPO_URL="$2"; shift ;;
    --bin-dir) BIN_DIR="$2"; shift ;;
    --config-dir) CONFIG_DIR="$2"; ENV_FILE="$CONFIG_DIR/env" ;;
    --env-file) ENV_FILE="$2" ;;
    --no-codex-profile) INSTALL_CODEX_PROFILE=0 ;;
    -h|--help|-H)
      cat <<'USAGE'
Usage: scripts/install.sh [options]

Options:
  --dry-run              Print actions without applying changes
  --non-interactive      Do not prompt; use environment/default values
  --install-dir DIR      Installation directory
  --repo-url URL         Git repository URL
  --bin-dir DIR          Directory for dsproxy wrapper
  --config-dir DIR       Config directory
  --env-file FILE        Env file path
  --no-codex-profile     Skip Codex profile installation
  -h, -H, --help         Show help

Interactive prompts:
  Stable proxy port
  Thinking proxy port
  DeepSeek API key, hidden input

The API key is written to a chmod 600 env file. Input is hidden, but this is
not cryptographic encryption.
USAGE
      exit 0
      ;;
    *) echo "ERROR: unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

run() {
  echo "+ $*"
  if [ "$DRY_RUN" = "0" ]; then
    "$@"
  fi
}

read_from_tty() {
  local prompt="$1"
  local default_value="${2:-}"
  local value=""

  if [ "$NON_INTERACTIVE" = "1" ] || [ ! -r /dev/tty ]; then
    printf '%s\n' "$default_value"
    return 0
  fi

  if [ -n "$default_value" ]; then
    printf "%s [%s]: " "$prompt" "$default_value" > /dev/tty
  else
    printf "%s: " "$prompt" > /dev/tty
  fi
  IFS= read -r value < /dev/tty || true
  if [ -z "$value" ]; then
    value="$default_value"
  fi
  printf '%s\n' "$value"
}

read_secret_from_tty() {
  local prompt="$1"
  local default_value="${2:-}"
  local value=""

  if [ "$NON_INTERACTIVE" = "1" ] || [ ! -r /dev/tty ]; then
    printf '%s\n' "$default_value"
    return 0
  fi

  if [ -n "$default_value" ]; then
    printf "%s [hidden, press Enter to keep existing]: " "$prompt" > /dev/tty
  else
    printf "%s [hidden]: " "$prompt" > /dev/tty
  fi

  stty -echo < /dev/tty 2>/dev/null || true
  IFS= read -r value < /dev/tty || true
  stty echo < /dev/tty 2>/dev/null || true
  printf "\n" > /dev/tty

  if [ -z "$value" ]; then
    value="$default_value"
  fi
  printf '%s\n' "$value"
}

write_env_file() {
  local stable_port="$1"
  local thinking_port="$2"
  local api_key="$3"

  run mkdir -p "$(dirname "$ENV_FILE")"

  if [ "$DRY_RUN" = "1" ]; then
    echo "+ write $ENV_FILE with chmod 600"
    return 0
  fi

  {
    printf '# deepseek-responses-proxy local environment\n'
    printf '# Generated by scripts/install.sh\n'
    printf 'export DEEPSEEK_API_KEY=%q\n' "$api_key"
    printf 'export DEEPSEEK_PROXY_PORT=%q\n' "$stable_port"
    printf 'export DEEPSEEK_PROXY_THINKING_PORT=%q\n' "$thinking_port"
    printf 'export DEEPSEEK_PROXY_MODEL=%q\n' "deepseek-v4-pro"
    printf 'export DEEPSEEK_REASONING_EFFORT=%q\n' "xhigh"
    printf 'export DEEPSEEK_PROXY_FORCE_MODEL=%q\n' "1"
    printf 'export DEEPSEEK_PROXY_TOOL_MAX_ROUNDS=%q\n' "6"
    printf 'export DEEPSEEK_PROXY_COMPACT_POLICY=%q\n' "adaptive"
    printf 'export DEEPSEEK_PROXY_AGENT_LIVENESS_GUARD=%q\n' "1"
    printf 'export DEEPSEEK_PROXY_AGENT_LIVENESS_JUDGE_ENABLED=%q\n' "1"
    printf 'export DEEPSEEK_PROXY_AGENT_LIVENESS_JUDGE_MODEL=%q\n' "v4-flash-no-thinking"
    printf 'export DEEPSEEK_PROXY_CODEX_TOOL_PROTOCOL_INSTRUCTION=%q\n' "1"
  } > "$ENV_FILE"

  chmod 600 "$ENV_FILE"
}

echo "CoDeepSeedeX installer"
echo "INSTALL_DIR=$INSTALL_DIR"
echo "REPO_URL=$REPO_URL"
echo "BIN_DIR=$BIN_DIR"
echo "ENV_FILE=$ENV_FILE"
echo "DRY_RUN=$DRY_RUN"

python3 - <<'PY'
import sys
if sys.version_info < (3, 11):
    raise SystemExit("ERROR: Python >= 3.11 is required")
print("python =", sys.version.split()[0])
PY

if ! command -v git >/dev/null 2>&1; then
  echo "ERROR: git is required" >&2
  exit 1
fi

DEFAULT_STABLE_PORT="${DEEPSEEK_PROXY_PORT:-8000}"
DEFAULT_THINKING_PORT="${DEEPSEEK_PROXY_THINKING_PORT:-8001}"
STABLE_PORT="$(read_from_tty "Stable proxy port" "$DEFAULT_STABLE_PORT")"
THINKING_PORT="$(read_from_tty "Thinking proxy port" "$DEFAULT_THINKING_PORT")"
API_KEY="$(read_secret_from_tty "DeepSeek API key" "${DEEPSEEK_API_KEY:-}")"

if [ -z "$API_KEY" ]; then
  echo "WARNING: DEEPSEEK_API_KEY is empty. You must set it before using the proxy." >&2
fi

if [ -d "$INSTALL_DIR/.git" ]; then
  run git -C "$INSTALL_DIR" pull --ff-only
else
  run mkdir -p "$(dirname "$INSTALL_DIR")"
  run git clone "$REPO_URL" "$INSTALL_DIR"
fi

run python3 -m venv "$INSTALL_DIR/.venv"
run "$INSTALL_DIR/.venv/bin/python" -m pip install --upgrade pip
run "$INSTALL_DIR/.venv/bin/python" -m pip install -e "$INSTALL_DIR"

write_env_file "$STABLE_PORT" "$THINKING_PORT" "$API_KEY"

run mkdir -p "$BIN_DIR"
if [ "$DRY_RUN" = "0" ]; then
  cat > "$BIN_DIR/dsproxy" <<EOF
#!/usr/bin/env bash
set -euo pipefail
ENV_FILE="\${DEEPSEEK_PROXY_ENV_FILE:-$ENV_FILE}"
if [ -f "\$ENV_FILE" ]; then
  source "\$ENV_FILE"
fi
exec "$INSTALL_DIR/.venv/bin/dsproxy" "\$@"
EOF
  chmod +x "$BIN_DIR/dsproxy"
else
  echo "+ write $BIN_DIR/dsproxy"
fi

run "$INSTALL_DIR/.venv/bin/dsproxy" config init

if [ "$INSTALL_CODEX_PROFILE" = "1" ]; then
  run "$INSTALL_DIR/.venv/bin/dsproxy" install-codex-profile \
    --base-url "http://127.0.0.1:${THINKING_PORT}/v1"
fi

echo
echo "Installed."
echo
echo "If $BIN_DIR is not on PATH, add it first:"
echo "  export PATH=\"$BIN_DIR:\$PATH\""
echo
echo "Basic commands:"
echo "  dsproxy --version"
echo "  dsproxy balance"
echo "  dsproxy config show"
echo "  dsproxy config set-model deepseek-v4-flash"
echo "  dsproxy config set-effort high"
echo "  dsproxy doctor --thinking --allow-down"
echo "  dsproxy start --thinking"
echo "  codex --profile deepseek-thinking"
echo
echo "Continue a previous Codex conversation:"
echo "  codex --profile deepseek-thinking resume"
echo
echo "Stop the proxy:"
echo "  dsproxy stop --thinking"
